# Plugin made by QuangDev05
# Plugin is already at version '${project.version}'
# Facebook: https://www.facebook.com/quangdev05.2024
# Discord: quangdev05
# Discord Community: https://discord.gg/MdgvJnegbM
# Github: https://github.com/PhamQuang2008/GiftCode
# Spigot: https://www.spigotmc.org/resources/giftcode24.117453/
# BuiltByBit: https://builtbybit.com/resources/giftcode24.46671/

messages:
  invalid-code: "The gift code you entered is invalid."
  expired-code: "The gift code you entered has expired."
  max-uses-reached: "The gift code you entered has reached its maximum number of uses."
  code-disabled: "The gift code you entered is currently disabled."
  code-redeemed: "You have successfully redeemed the gift code!"
  code-already-redeemed: "You have already redeemed this code."

