name: GiftCode24
version: '${project.version}'
main: quangdev05.giftcode24.GiftCode24
api-version: 1.12
load: STARTUP
authors:
  - QuangDev05
description: GiftCodePlugin is a Minecraft plugin that allows you to manage and use gift codes on your server. The plugin provides commands for admins to create, enable/disable, and reload gift codes, as well as commands for players to redeem codes and receive rewards.

commands:
  giftcode:
    description: Manage gift codes
    usage: /<command>
    permission: giftcode.admin
    aliases: [gc]
  code:
    description: Redeem a gift code
    usage: /<command>
    permission: giftcode.player
permissions:
  giftcode.admin:
    description: Allows use of admin gift code commands
    default: op
  giftcode.player:
    description: Allows players to redeem gift codes
    default: true
